import { DesignSystem } from './types'

function uniqueFamilies(system: DesignSystem): string[] {
  return [...new Set(system.typography.map((t) => t.family))]
}

export function toCssVars(system: DesignSystem): string {
  const lines: string[] = [
    `/* ============================================================`,
    `   ${system.name} — Design Tokens`,
    `   Source: ${system.source}`,
    `   Generated by Datrycs Design System Browser`,
    `   ============================================================ */`,
    ``,
  ]

  // Font family hints (not @font-face — host those yourself)
  const families = uniqueFamilies(system)
  if (families.length) {
    lines.push(`:root {`)
    lines.push(`  /* ── Font Families (${families.length}) ── */`)
    families.forEach((f, i) => {
      const key = i === 0 ? 'display' : i === 1 ? 'body' : `font-${i}`
      lines.push(`  --font-family-${key}: '${f}', system-ui, sans-serif;`)
    })
  } else {
    lines.push(`:root {`)
  }

  // Colors
  lines.push(``)
  lines.push(`  /* ── Colors (${system.colors.length}) ── */`)
  let lastGroup = ''
  for (const c of system.colors) {
    if (c.group !== lastGroup) {
      lines.push(`  /* ${c.group} */`)
      lastGroup = c.group
    }
    lines.push(`  --${c.token}: ${c.hex};`)
  }

  // Spacing
  lines.push(``)
  lines.push(`  /* ── Spacing (${system.spacing.length}) ── */`)
  for (const s of system.spacing) {
    lines.push(`  --${s.token}: ${s.value}px;`)
  }

  // Radius
  lines.push(``)
  lines.push(`  /* ── Border Radius (${system.radius.length}) ── */`)
  for (const r of system.radius) {
    lines.push(`  --${r.token}: ${r.value === 9999 ? '9999px' : `${r.value}px`};`)
  }

  // Typography tokens
  lines.push(``)
  lines.push(`  /* ── Typography Tokens (${system.typography.length}) ── */`)
  for (const t of system.typography) {
    lines.push(`  --font-size-${t.token}: ${t.size}px;`)
    lines.push(`  --font-weight-${t.token}: ${t.weight};`)
    lines.push(`  --line-height-${t.token}: ${t.lineHeight}px;`)
    if (t.tracking !== 0) lines.push(`  --letter-spacing-${t.token}: ${t.tracking}px;`)
  }

  lines.push(`}`)

  // Typography utility classes
  lines.push(``)
  lines.push(`/* ── Typography Utility Classes ── */`)
  lines.push(`/* Apply these directly: <h1 class="type-h1"> or extend with @apply */`)
  for (const t of system.typography) {
    const familyIndex = families.indexOf(t.family)
    const familyKey = familyIndex === 0 ? 'display' : familyIndex === 1 ? 'body' : `font-${familyIndex}`
    const parts = [
      `  font-family: var(--font-family-${familyKey});`,
      `  font-size: var(--font-size-${t.token});`,
      `  font-weight: var(--font-weight-${t.token});`,
      `  line-height: var(--line-height-${t.token});`,
    ]
    if (t.tracking !== 0) parts.push(`  letter-spacing: var(--letter-spacing-${t.token});`)
    lines.push(``)
    lines.push(`.type-${t.token} {`)
    lines.push(...parts)
    lines.push(`}`)
  }

  return lines.join('\n')
}

export function toCssSection(system: DesignSystem, section: 'colors' | 'typography' | 'spacing' | 'radius'): string {
  const header = [
    `/* ============================================================`,
    `   ${system.name} — ${section.charAt(0).toUpperCase() + section.slice(1)} Tokens`,
    `   Source: ${system.source}`,
    `   ============================================================ */`,
    ``,
  ]

  if (section === 'colors') {
    const lines = [...header, `:root {`]
    let lastGroup = ''
    for (const c of system.colors) {
      if (c.group !== lastGroup) { lines.push(`  /* ${c.group} */`); lastGroup = c.group }
      lines.push(`  --${c.token}: ${c.hex};`)
    }
    lines.push(`}`)
    return lines.join('\n')
  }

  if (section === 'spacing') {
    const lines = [...header, `:root {`]
    for (const s of system.spacing) lines.push(`  --${s.token}: ${s.value}px; /* ${s.usage} */`)
    lines.push(`}`)
    return lines.join('\n')
  }

  if (section === 'radius') {
    const lines = [...header, `:root {`]
    for (const r of system.radius) lines.push(`  --${r.token}: ${r.value === 9999 ? '9999px' : `${r.value}px`}; /* ${r.usage} */`)
    lines.push(`}`)
    return lines.join('\n')
  }

  if (section === 'typography') {
    const families = uniqueFamilies(system)
    const lines = [...header, `:root {`]
    families.forEach((f, i) => {
      const key = i === 0 ? 'display' : i === 1 ? 'body' : `font-${i}`
      lines.push(`  --font-family-${key}: '${f}', system-ui, sans-serif;`)
    })
    lines.push(``)
    for (const t of system.typography) {
      lines.push(`  --font-size-${t.token}: ${t.size}px;`)
      lines.push(`  --font-weight-${t.token}: ${t.weight};`)
      lines.push(`  --line-height-${t.token}: ${t.lineHeight}px;`)
      if (t.tracking !== 0) lines.push(`  --letter-spacing-${t.token}: ${t.tracking}px;`)
    }
    lines.push(`}`)
    lines.push(``)
    lines.push(`/* ── Typography Utility Classes ── */`)
    for (const t of system.typography) {
      const familyIndex = families.indexOf(t.family)
      const familyKey = familyIndex === 0 ? 'display' : familyIndex === 1 ? 'body' : `font-${familyIndex}`
      const parts = [
        `  font-family: var(--font-family-${familyKey});`,
        `  font-size: var(--font-size-${t.token});`,
        `  font-weight: var(--font-weight-${t.token});`,
        `  line-height: var(--line-height-${t.token});`,
      ]
      if (t.tracking !== 0) parts.push(`  letter-spacing: var(--letter-spacing-${t.token});`)
      lines.push(``)
      lines.push(`.type-${t.token} {`)
      lines.push(...parts)
      lines.push(`}`)
    }
    return lines.join('\n')
  }

  return ''
}

export function toJson(system: DesignSystem): string {
  const tokens: Record<string, Record<string, unknown>> = {
    color: {},
    spacing: {},
    radius: {},
    typography: {},
  }

  for (const c of system.colors) {
    tokens.color[c.token] = { value: c.hex, role: c.role, group: c.group }
  }
  for (const s of system.spacing) {
    tokens.spacing[s.token] = { value: `${s.value}px`, usage: s.usage }
  }
  for (const r of system.radius) {
    tokens.radius[r.token] = { value: r.value === 9999 ? '9999px' : `${r.value}px`, usage: r.usage }
  }
  for (const t of system.typography) {
    tokens.typography[t.token] = {
      fontFamily: t.family,
      fontSize: `${t.size}px`,
      fontWeight: t.weight,
      lineHeight: `${t.lineHeight}px`,
      letterSpacing: t.tracking !== 0 ? `${t.tracking}px` : '0',
      usage: t.usage,
    }
  }

  return JSON.stringify(tokens, null, 2)
}

// ── Shopware-specific color token → $sw-* variable mapping ──────────────────
const SW_COLOR_MAP: Record<string, string> = {
  'brand-primary':    'sw-color-brand-primary',
  'brand-secondary':  'sw-color-brand-secondary',
  'surface-default':  'sw-background-color',
  'text-primary':     'sw-text-color',
  'text-heading':     'sw-headline-color',
  'border-default':   'sw-border-color',
  'semantic-success': 'sw-color-success',
  'semantic-info':    'sw-color-info',
  'semantic-warning': 'sw-color-warning',
  'semantic-error':   'sw-color-danger',
  'price':            'sw-color-price',
  'buy-button-bg':    'sw-color-buy-button',
  'buy-button-text':  'sw-color-buy-button-text',
}

const SW_COLOR_DEFAULTS: Record<string, string> = {
  'sw-color-brand-primary':   '#0042a0',
  'sw-color-brand-secondary': '#474a57',
  'sw-background-color':      '#ffffff',
  'sw-text-color':            '#2b3136',
  'sw-headline-color':        '#2b3136',
  'sw-border-color':          '#798490',
  'sw-color-success':         '#007e4e',
  'sw-color-info':            '#005b99',
  'sw-color-warning':         '#974200',
  'sw-color-danger':          '#c20017',
  'sw-color-price':           '#2b3136',
  'sw-color-buy-button':      '#0042a0',
  'sw-color-buy-button-text': '#ffffff',
}

const SW_HEADING_TOKEN_MAP: Record<string, { bsVar: string; swDefault: string }> = {
  'display-xl': { bsVar: 'h1-font-size', swDefault: '36px' },
  'display-lg': { bsVar: 'h2-font-size', swDefault: '28px' },
  'display-md': { bsVar: 'h3-font-size', swDefault: '24px' },
  'display-sm': { bsVar: 'h4-font-size', swDefault: '20px' },
  'title-lg':   { bsVar: 'h5-font-size', swDefault: '16px' },
  'title-md':   { bsVar: 'h6-font-size', swDefault: '14px' },
}

export function toShopwareScss(system: DesignSystem): string {
  const lines: string[] = [
    `// ============================================================`,
    `// Variables — ${system.name} (Shopware 6 Storefront)`,
    `// Generated by Datrycs Design System Browser`,
    `// Source: ${system.source}`,
    `// Variable reference: https://datrycs-ds.vercel.app/mappings/shopware.json`,
    `// ============================================================`,
    `//`,
    `// USAGE:`,
    `//   Option A (recommended): Set sw-* values in theme.json config.fields`,
    `//                           → use the "theme.json" export tab instead`,
    `//   Option B (plugin SCSS): Include this file BEFORE Shopware's variables.scss`,
    `//`,
    `// !! Do NOT use !default — Shopware already sets these with !default.`,
    `//    Adding !default here means your values get ignored.`,
    `// ============================================================`,
    ``,
    `// ── Section 1: Shopware theme variables ($sw-*) ─────────────`,
    `// Prefer theme.json config.fields — see "theme.json fields" export tab.`,
    `// Only keep Section 1 here if no theme.json is available in your project.`,
    ``,
  ]

  for (const c of system.colors) {
    const swVar = SW_COLOR_MAP[c.token]
    if (!swVar) continue
    const def = SW_COLOR_DEFAULTS[swVar] ?? ''
    const noChange = def.toLowerCase() === c.hex.toLowerCase()
    const comment = noChange
      ? `  // SW default: ${def} — no change`
      : `  // SW default: ${def}`
    const padding = ' '.repeat(Math.max(1, 28 - swVar.length))
    lines.push(`$${swVar}:${padding}${c.hex};${comment}`)
  }

  const families = uniqueFamilies(system)
  const baseFont = families[0] ?? 'system-ui'
  const headlineFont = families.length > 1 ? families[1] : families[0] ?? 'system-ui'
  lines.push(``)
  lines.push(`$sw-font-family-base:      '${baseFont}', system-ui, -apple-system, sans-serif;  // SW default: 'Inter', sans-serif`)
  lines.push(`$sw-font-family-headline:  '${headlineFont}', system-ui, sans-serif;             // SW default: 'Inter', sans-serif`)

  lines.push(``)
  lines.push(`// ── Section 2: Bootstrap 5 overrides ────────────────────────`)
  lines.push(`// NOT in theme.json — must be set here.`)
  lines.push(`// SW defaults: h1=36px h2=28px h3=24px h4=20px h5=16px h6=14px`)
  lines.push(``)

  for (const [tokenName, { bsVar, swDefault }] of Object.entries(SW_HEADING_TOKEN_MAP)) {
    const typoToken = system.typography.find(t => t.token === tokenName)
    if (!typoToken) continue
    const noChange = `${typoToken.size}px` === swDefault
    const comment = noChange
      ? `  // SW default: ${swDefault} — no change`
      : `  // SW default: ${swDefault}`
    const padding = ' '.repeat(Math.max(1, 22 - bsVar.length))
    lines.push(`$${bsVar}:${padding}${typoToken.size}px;${comment}`)
  }

  const bodyMd = system.typography.find(t => t.token === 'body-md')
  if (bodyMd) {
    const remVal = Math.round((bodyMd.size / 16) * 10000) / 10000
    const remStr = remVal % 1 === 0 ? `${remVal}.0rem` : `${remVal}rem`
    const lhRatio = Math.round((bodyMd.lineHeight / bodyMd.size) * 100) / 100
    const noChange16 = bodyMd.size === 16
    lines.push(``)
    lines.push(`$font-size-base:       ${remStr};  // ${bodyMd.size}px${noChange16 ? ' — SW default: 1rem (16px) — no change' : ' at 16px root; SW default: 1rem (16px)'}`)
    lines.push(`$font-weight-normal:   ${bodyMd.weight};`)
    const displayToken = system.typography.find(t => t.token === 'display-xl' || t.token === 'display-lg')
    if (displayToken) lines.push(`$headings-font-weight: ${displayToken.weight};`)
    lines.push(`$line-height-base:     ${lhRatio};  // ${bodyMd.lineHeight}px / ${bodyMd.size}px`)
  }

  return lines.join('\n')
}

export function toShopwareThemeFields(system: DesignSystem): string {
  const fields: Record<string, { type: string; value: string }> = {}

  for (const c of system.colors) {
    const swVar = SW_COLOR_MAP[c.token]
    if (swVar) fields[swVar] = { type: 'color', value: c.hex }
  }

  const families = uniqueFamilies(system)
  if (families.length > 0) {
    const base = families[0]
    const headline = families.length > 1 ? families[1] : families[0]
    fields['sw-font-family-base']     = { type: 'fontFamily', value: `'${base}', system-ui, -apple-system, sans-serif` }
    fields['sw-font-family-headline'] = { type: 'fontFamily', value: `'${headline}', system-ui, sans-serif` }
  }

  const output = {
    _note: `${system.name} — Shopware theme.json fields. Paste into your child theme's theme.json under config.fields. Bootstrap overrides (heading sizes etc.) cannot be set here — use the SCSS export tab instead.`,
    config: { fields },
  }

  return JSON.stringify(output, null, 2)
}

export function toTailwind(system: DesignSystem): string {
  const colors: Record<string, string> = {}
  for (const c of system.colors) {
    colors[c.token] = c.hex
  }

  const spacing: Record<string, string> = {}
  for (const s of system.spacing) {
    spacing[s.token.replace('spacing-', '')] = `${s.value}px`
  }

  const borderRadius: Record<string, string> = {}
  for (const r of system.radius) {
    borderRadius[r.token.replace('radius-', '')] = r.value === 9999 ? '9999px' : `${r.value}px`
  }

  const families = uniqueFamilies(system)
  const fontFamily: Record<string, string[]> = {}
  families.forEach((f, i) => {
    const key = i === 0 ? 'display' : i === 1 ? 'body' : `font-${i}`
    fontFamily[key] = [f, 'system-ui', 'sans-serif']
  })

  const fontSize: Record<string, [string, { lineHeight: string; fontWeight: string }]> = {}
  for (const t of system.typography) {
    fontSize[t.token] = [`${t.size}px`, { lineHeight: `${t.lineHeight}px`, fontWeight: `${t.weight}` }]
  }

  const config = {
    theme: {
      extend: {
        colors,
        spacing,
        borderRadius,
        fontFamily,
        fontSize,
      },
    },
  }

  return `/** @type {import('tailwindcss').Config} */\nmodule.exports = ${JSON.stringify(config, null, 2)}`
}
